FROM node:14-alpine AS builder
WORKDIR /builder
COPY . /builder/
RUN echo $ENV_FILE | base64 --decode > /builder/.env
RUN yarn && yarn build

FROM node:14-alpine as app
WORKDIR /app
COPY --from=builder /builder/build /app/build/
RUN yarn global add serve
CMD [ "sh", "-c", "serve -s build -l $PORT" ]