version: 2.1
orbs:
  heroku: circleci/heroku@1.2.2
  slack: circleci/slack@4.1

jobs:
  build:
    docker:
      - image: circleci/node:14-buster
    steps:
      - checkout
      - run:
          name: Setup Env
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=iptv-sampler' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: false
          version: 19.03.13
      - heroku/install
      - run:
          command: 'heroku container:login'
          name: Login to Heroku Docker image registry
      - run:
          command: >
            heroku container:push -a $HEROKU_APP_NAME --arg ENV_FILE=$ENV_FILE --recursive
          name: Push Docker image to Heroku
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - heroku/release-docker-image:
          no_output_timeout: 3m

  
workflows:
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main