import React from 'react';
import { v4 as uuidv4 } from 'uuid';
import { List, ListItemButton, ListItemText } from '@mui/material';
import data from './channels.json';

// Generated by https://quicktype.io

export interface Channel {
    name:      string;
    logo:      null | string;
    url:       string;
    category:  null | string;
    languages: Country[];
    countries: Country[];
    tvg:       Tvg;
}

export interface Country {
    code: string;
    name: string;
}

export interface Tvg {
    id:   null | string;
    name: string;
    url:  null | string;
}


export interface IChannelsListProp {
    onItemClick: (url: string) => void
}

const ChannelsList: React.FC<IChannelsListProp> = ({onItemClick}) => {
    const selectedChannels = (data as Channel[]);
    const channelItems = selectedChannels.map((ch) => {
        return (
            <ListItemButton
                key={uuidv4()} 
                onClick={() => onItemClick(ch.url)}
            >
                <ListItemText primary={ch.name}/>
            </ListItemButton>
        )
    })

    return (
        <List>
            {channelItems}
        </List>
    )
}

export default ChannelsList;